### PR TITLE
Created the Kanban Board Setup

### PR DESCRIPTION
**Pull request by AsimKhan2019**
Thanks to our coding Partner Brian Nyachae, we were able to complete the Kanban Board task for today: 

Our Git Hub Project Link is 
https://github.com/AsimKhan2019/Catalog_of_Things/tree/kanban-board

Although we are still in the development phase, the entire project will be visible in the main branch once we have completed all the relevant tasks and merged it with the main branch after the approval. 

Team Member 1 (Asim Mehmood Khan) has been assigned the following tasks:
Create Item's class and association
Create Book Class 
Create Music Data in JSON
Create Database Schema 

Team Member 2 (Fadahunsi Samuel) has been assigned the following tasks: 
Create Item's class and association
Create Music Album Class 
Implement Startup options 
Preserve Game data in JSON 
Add Database schema 

Team Member 3 (Brian Nyachae) has been assigned the following tasks: 
Create Item's class and association
Create Game Class 
Preserve Book Data in JSON
Add Database schema

Since we are 3 team members, we skipped the Movie class and its relevant tasks and association, as it was to be assigned to the fourth member. 

Kindly please approve this board.

### CODE REVIEW

**Comment by Munsa1** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Kindly add a Link to your Github project in the description as well as this is a core requirement.
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AsimKhan2019** [comment]
@Munsa1 Thank you for the feedback I added the GitHub project link in the read-me file.

**Comment by Munsa1** [comment]
> @Munsa1 Thank you for the feedback I added the GitHub project link in the read-me file.

> Check the screenshot above, it should be added to the description the screenshot below
image

**Comment by AsimKhan2019** [comment]
@Munsa1 So sorry about the confusion, please check the description again. I have added the link to the project.

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi @AsimKhan2019, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 

## Highlights 💪 
- No linter errors
- correct flow is used

## Required Changes ♻️

- [ ] Good job so far 👏 I appreciate your effort in setting up your kanban project well. I am sorry for the confusion made but from the project requirements, you are expected to communicate with the reviewers using the issues. As you did before, you open an issue and you put all the info about the team and the link to your Kanban project 😃 👍
image

So please follow the procedures given 😎 


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@BertrandConxy Should I create a new issue in my repository and then share that issue in the review?

**Comment by BertrandConxy** [comment]
yeah sure
Make sure you include the information required

**Comment by AsimKhan2019** [comment]
@BertrandConxy Thank you

**Comment by AsimKhan2019** [comment]
@BertrandConxy Is this ok? 

https://github.com/AsimKhan2019/Catalog_of_Things/issues/17

I do not want to waste another review over my confusion.

**Comment by BertrandConxy** [comment]
@AsimKhan2019 Please add the link to your Kanban board project

Not that one you added

**Comment by AsimKhan2019** [comment]
@BertrandConxy I just updated the link in the issue. I updated it to 

https://github.com/AsimKhan2019/Catalog_of_Things/projects/1

I am so sorry for my misunderstanding again

**Comment by BertrandConxy** [comment]
@AsimKhan2019 I think now you are good to go 😃 🏃

**Comment by BertrandConxy** [comment]
You will need to ask for another review

**Comment by AsimKhan2019** [comment]
@BertrandConxy Thank you for the clarity brother.

**Pull request merged**
